### ISSUE TITLE
Zoopla are removing HTTP endpoint and replacing with HTTPS

### ISSUE THREAD

**Issue by dtaylor7** [InsidersByte/zoopla#3]
Just received email from Zoopla:

> To Whom it May Concern,
>  
> Zoopla values its security and one of the steps we have taken to ensure this is to secure the Public API. We do realise that this may require changes in the settings on your platform, therefore we are planning to switch off http://api.zoopla.co.uk  June 2017.
>  
> From June 2017 the Zoopla public API will be only accessible from https://api.zoopla.co.uk.
>  
> For further details on the Zoopla API please refer to the documentation on: https://developer.zoopla.co.uk.
>  
> For technical support please email api@zoopla.co.uk
>  
> Thanks,
> The Zoopla Team

Can you add https ability to endpoint?

**Comment by InsidersByte** [comment]
sure

**Comment by InsidersByte** [comment]
done 👍
